trigger: 
  - main

pool:
  vmImage: ubuntu-latest

# resources:
#   repositories:
#     - repository: contact_ui_ng_app
#       type: github
#       endpoint: saikrishnap123
#       name: saikrishnap123/contact_ui_ng_app
#       ref: main
variables:
  tag: "$(Build.BuildId)"

stages:
- stage: buildStage
  jobs:
  - job: buildJob 
    steps:
    - checkout: self  

    - task: Docker@2
      displayName: 'Build and push Docker image to Docker Hub'
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'Docker Hub'  
        repository: 'docker15139/frontend-angular'  
        tags: tag
